katl: "KATL"
kclt: "KCLT"
kden: "KDEN"
kdfw: "KDFW"
kjfk: "KJFK"
kmem: "KMEM"
kmia: "KMIA"
kord: "KORD"
kphx: "KPHX"
ksea: "KSEA"

start_time: "2020-11-01"
end_time: "2022-12-02"
target_name: "minutes_until_pushback"
end_train: "2022-09-01"
