from typing import Final

# the column used for target
TARGET_LABEL: str = "minutes_until_pushback"

ALL_AIRPORTS: Final[list[str]] = [
    "KATL",
    "KCLT",
    "KDEN",
    "KDFW",
    "KJFK",
    "KMEM",
    "KMIA",
    "KORD",
    "KPHX",
    "KSEA",
    # "ALL",
]

AIRLINES: Final[list[str]] = [
    "AAL",
    "AJT",
    "ASA",
    "ASH",
    "AWI",
    "DAL",
    "EDV",
    "EJA",
    "ENY",
    "FDX",
    "FFT",
    "GJS",
    "GTI",
    "JBU",
    "JIA",
    "NKS",
    "PDT",
    "QXE",
    "RPA",
    "SKW",
    "SWA",
    "SWQ",
    "TPA",
    "UAL",
    "UPS",
]


CATEGORICAL_STR_CATEGORIES: Final[dict[str, list[str]]] = {
    "airport": ALL_AIRPORTS,
    "cloud": ["UNK", "BK", "CL", "FEW", "OV", "SC"],
    "lightning_prob": ["UNK", "N", "L", "M", "H"],
    "precip": ["UNK", "False", "True"],
    "departure_runways": [
        "UNK",
        "26L, 27R",
        "26L, 27R, 28",
        "8R, 9L",
        "26L, 27R, 8R",
        "26L, 27L, 27R, 28",
        "8R, 9L, 9R",
        "10, 8R, 9L",
        "26L, 27L, 27R",
        "9L",
        "8R, 9R",
        "26L, 27R, 8R, 9L",
        "26L, 27L",
        "8L, 8R, 9L",
        "26R, 27R",
        "26L, 26R, 27R",
        "26L",
        "27R, 28",
        "10, 9L",
        "26L, 28",
        "10, 8R",
        "10, 8R, 9R",
        "27R",
        "8L, 9L",
        "26R, 27L",
        "8L, 9R",
        "10, 8L, 8R",
        "26L, 26R, 27L",
        "27L",
        "8R",
        "27R, 9L",
        "27R, 8R, 9L",
        "10, 9L, 9R",
        "26R, 27L, 28",
        "10, 8L",
        "26R, 28",
        "27L, 28",
        "26L, 27L, 28",
        "9R",
        "8L",
        "10, 8L, 9R",
        "26R, 27R, 28",
        "10, 27R, 28, 9L",
        "26R, 27L, 27R",
        "28, 8R, 9L",
        "10, 8L, 9L",
        "26L, 27L, 8R, 9R",
        "10, 8L, 8R, 9R",
        "26L, 27R, 9L",
        "26R",
        "10, 26L, 28, 8R",
        "10, 9R",
        "10, 8R, 9L, 9R",
        "26L, 26R, 27R, 28",
        "26L, 8R",
        "18C, 18L",
        "36C, 36R",
        "36C",
        "36R",
        "18C",
        "18L",
        "36C, 36L, 36R",
        "36C, 36L",
        "18C, 18L, 18R",
        "18C, 18R",
        "36L, 36R",
        "5",
        "25, 34L, 34R",
        "25, 34L",
        "17L, 25, 8",
        "17L, 17R, 25, 8",
        "25, 34L, 8",
        "25, 8",
        "17L, 17R, 8",
        "17L, 8",
        "34L, 8",
        "16L, 25",
        "25, 34R, 8",
        "25, 34R",
        "17L, 17R",
        "17L, 25",
        "17R",
        "34R, 8",
        "17R, 8",
        "25",
        "17L",
        "34L",
        "34L, 35L",
        "34L, 34R",
        "34R, 35L",
        "34L, 34R, 35L, 8",
        "34R",
        "34L, 35L, 8",
        "34L, 34R, 35L",
        "35L",
        "8",
        "35L, 8",
        "26, 34L",
        "34R, 35L, 8",
        "34L, 34R, 8",
        "16L, 17R",
        "17L, 17R, 25",
        "25, 34L, 34R, 8",
        "16L, 25, 8",
        "17R, 25, 8",
        "17R, 25",
        "16R",
        "25, 34L, 34R, 35L",
        "16L, 17L, 8",
        "16L, 8",
        "16L",
        "16L, 17L",
        "16L, 17L, 25",
        "16R, 8",
        "16L, 17L, 25, 8",
        "25, 26, 34L",
        "17L, 17R, 25, 34L, 34R",
        "17R, 25, 34R",
        "25, 35L, 8",
        "7",
        "17L, 34L, 8",
        "17L, 17R, 25, 34R",
        "31L, 35C, 35L, 36R",
        "17R, 18L",
        "31L, 35L, 36R",
        "35L, 36R",
        "31L, 35L",
        "17C, 17R, 18L",
        "17C, 18L",
        "17C, 17R, 18L, 18R",
        "35L, 36L, 36R",
        "17R, 18R",
        "17R, 18L, 18R",
        "17C",
        "31R",
        "17C, 18R",
        "35C, 36R",
        "35L, 36L",
        "17C, 17R",
        "17C, 17R, 18R",
        "35C, 35L, 36L, 36R",
        "35C, 35L, 36R",
        "17C, 18L, 18R",
        "18L, 18R",
        "35C, 36L",
        "31R, 35C, 36R",
        "31R, 35L, 36R",
        "18R",
        "31L, 31R",
        "35C",
        "31L, 36R",
        "31L",
        "17L, 18L",
        "17L, 17R, 18L",
        "35C, 35L",
        "35C, 36L, 36R",
        "35R",
        "35C, 35L, 36L",
        "4L",
        "22R",
        "13R",
        "22R, 31L",
        "31L, 4L",
        "22R, 4L",
        "22L",
        "4R",
        "13L, 13R",
        "13L",
        "13L, 22R",
        "18C, 18L, 18R, 27",
        "27, 36C, 36L, 36R",
        "36L, 36R, 9",
        "27, 36L, 36R",
        "27, 36C",
        "27, 36C, 36L",
        "36R, 9",
        "36C, 36L, 36R, 9",
        "27, 36C, 36R",
        "36C, 36L, 9",
        "36L, 9",
        "36C, 36R, 9",
        "36C, 9",
        "18C, 18L, 27",
        "9",
        "18L, 18R, 27",
        "27",
        "27, 36R",
        "27, 36L",
        "18C, 18R, 27",
        "36L",
        "18C, 18L, 18R, 36C, 36L, 36R",
        "26L, 26R, 27, 30",
        "12, 8L, 8R, 9",
        "12, 8L, 8R",
        "26L, 26R, 27",
        "8L, 8R, 9",
        "8L, 9",
        "12, 9",
        "26L, 26R",
        "8R, 9",
        "12, 8R, 9",
        "8L, 8R",
        "26L, 27",
        "12, 8R",
        "26R, 27",
        "26L, 27, 30",
        "12, 8L, 9",
        "26L, 26R, 30",
        "26R, 27, 30",
        "27, 30",
        "22L, 28R",
        "10L, 9R",
        "10L, 9C",
        "10L",
        "10L, 4L",
        "28R, 4L",
        "22L, 9C",
        "10L, 22L, 9C",
        "22L, 27C, 28R",
        "22L, 28C",
        "27C, 28R",
        "28R",
        "10L, 4L, 9C",
        "10L, 4L, 9R",
        "22L, 27L, 28R",
        "28C",
        "22L, 27L",
        "22L, 9R",
        "10L, 22L, 9R",
        "9C, 9R",
        "27C, 28C",
        "10L, 22L",
        "22L, 4L",
        "9C",
        "22L, 27C",
        "22L, 27L, 28C",
        "10C",
        "22L, 28R, 4L",
        "27L, 28R",
        "22L, 27C, 28C",
        "10L, 22L, 4L",
        "27C",
        "10C, 9R",
        "4L, 9C",
        "10C, 9C",
        "10C, 22L",
        "10C, 22L, 9C",
        "27C, 27L",
        "10C, 22L, 9R",
        "27L, 28C",
        "10L, 9C, 9R",
        "22L, 28C, 28R",
        "28C, 28R",
        "27C, 27L, 28C, 9R",
        "10L, 22L, 4L, 9C",
        "27C, 28R, 9C",
        "10C, 4L",
        "10C, 4L, 9C",
        "10C, 10L",
        "25R",
        "7L",
        "7L, 7R",
        "7R",
        "7L, 7R, 8",
        "7R, 8",
        "25L, 25R",
        "25L, 26",
        "7L, 8",
        "25R, 7L",
        "25R, 26",
        "26",
        "25L, 25R, 26",
        "25L",
        "26, 7L, 8",
        "34C",
        "16C",
        "34C, 34R",
        "16C, 16L",
    ],
    "arrival_runways": [
        "UNK",
        "26R, 27L, 28",
        "10, 8L, 9R",
        "26R, 28",
        "26R, 27L",
        "9R",
        "8L, 9R",
        "10, 8L, 9L, 9R",
        "26R, 27R, 28",
        "10, 8L",
        "10, 9R",
        "10, 8L, 9L",
        "27L, 28",
        "26L, 27L, 28",
        "26L, 28",
        "8L",
        "10, 8R, 9R",
        "10, 8R, 9L",
        "26L, 27R, 28",
        "8L, 9L",
        "8R, 9L",
        "26L, 27R",
        "26R",
        "26R, 27R",
        "27L",
        "26L, 27L",
        "8R, 9R",
        "10, 8R",
        "10, 9L",
        "27R, 28",
        "10",
        "27R",
        "28",
        "9L",
        "8R",
        "18C, 18L, 18R",
        "36C, 36L, 36R",
        "36C, 36L",
        "36C, 36R",
        "18C, 18R",
        "18L, 18R",
        "36L, 36R",
        "36C",
        "18C, 18L",
        "18L",
        "36R",
        "18C",
        "5",
        "26, 34R, 35L, 35R",
        "34R, 35L, 35R",
        "16L, 16R, 17R, 25",
        "16L, 16R, 17R",
        "34R, 35R",
        "16L, 16R, 35L, 35R",
        "16R, 17L, 17R",
        "26, 35L, 35R",
        "16L, 26",
        "16L, 17R",
        "16L, 17R, 7",
        "16L, 17L",
        "35L, 35R",
        "35L, 35R, 7",
        "26, 34R, 35R",
        "16L, 35L, 35R",
        "35L",
        "16R, 17R",
        "34R, 35L",
        "17R",
        "16R",
        "16R, 17L",
        "35R",
        "17L",
        "16R, 35L, 35R",
        "16L, 16R, 17L, 17R",
        "16L, 16R",
        "16L, 16R, 26",
        "7",
        "35L, 7",
        "17L, 8",
        "16L",
        "17L, 17R",
        "7, 8",
        "16R, 17R, 7",
        "35R, 7",
        "34L, 35L, 35R",
        "25, 26",
        "26, 34R, 35L",
        "16L, 16R, 17R, 7",
        "16L, 17L, 17R",
        "16L, 17R, 26",
        "34R, 35L, 35R, 7",
        "26",
        "34R",
        "16L, 16R, 7",
        "16R, 26",
        "34L, 35R",
        "26, 35R",
        "34L, 35L",
        "26, 35L",
        "16L, 26, 35L, 35R",
        "16R, 7",
        "16L, 16R, 17R, 35R",
        "16L, 17R, 35R",
        "16R, 17R, 26",
        "26, 7",
        "16L, 16R, 35R",
        "16R, 17R, 35R, 7",
        "16L, 16R, 17L",
        "8",
        "16L, 7",
        "16L, 17L, 7",
        "26, 34R",
        "34L, 34R",
        "31R, 35C, 35R, 36R",
        "13R, 17C, 17L, 18L",
        "13R, 17C, 17L",
        "31R, 35C, 35R",
        "17C, 17L, 18L",
        "13R, 35C, 35R, 36R",
        "31R, 35C, 35R, 36L",
        "35C, 35R, 36R",
        "17C, 17L",
        "35C, 35R",
        "13R, 17C, 17L, 18R",
        "17C, 18L",
        "13R, 17C, 17L, 17R, 18L",
        "17C, 17L, 18R",
        "13R, 17C, 17R, 18L, 18R",
        "35C, 35R, 36L",
        "17C",
        "13R, 17C, 17L, 17R, 18R",
        "13R, 17L, 18R",
        "17C, 18R",
        "35C, 35L, 36L, 36R",
        "31R, 35C, 35R, 36L, 36R",
        "17C, 17R, 18R",
        "35L, 36R",
        "35C, 36R",
        "35C, 36L",
        "13R, 17C, 18R",
        "17L, 17R, 18L, 18R",
        "17C, 17R, 18L, 18R",
        "13R, 35C, 35R, 36L",
        "17C, 17L, 18R, 31R",
        "17L, 18R",
        "13R, 17C, 18L",
        "13L, 17C, 17L, 18L",
        "31R, 35C, 36L",
        "17C, 17L, 17R, 18L, 18R",
        "13R, 18L",
        "17R, 18L",
        "35C",
        "13R, 18R",
        "35C, 35L, 35R, 36L, 36R",
        "17L, 17R, 18L",
        "31L",
        "13R, 17C, 17L, 17R, 18L, 18R",
        "17R, 18L, 18R",
        "31R, 35C, 35L, 36L, 36R",
        "31R, 35C, 35L, 35R, 36L, 36R",
        "17C, 17R",
        "17C, 18L, 18R",
        "35R, 36R",
        "35C, 35L, 36L",
        "13R, 18L, 18R",
        "17C, 17R, 18L",
        "17R, 18R",
        "35C, 35L, 36R",
        "35L, 36L, 36R",
        "35C, 35L",
        "17L, 18L",
        "13R, 35C, 36L",
        "18R",
        "31L, 31R",
        "31R, 35C, 36R",
        "13R, 17L, 18L",
        "13R, 17C",
        "31R, 35C",
        "13R, 17C, 17L, 18L, 18R",
        "31L, 31R, 35C, 35R",
        "35R, 36L",
        "35C, 36L, 36R",
        "17L, 17R, 18R",
        "35L, 36L",
        "13L, 17C, 17L, 18R",
        "17C, 17L, 17R, 18R",
        "36L",
        "35C, 35L, 35R, 36R",
        "13R, 17R, 18L",
        "17C, 17L, 17R",
        "17C, 17L, 18L, 18R",
        "17C, 17L, 17R, 18L",
        "35C, 35L, 35R, 36L",
        "35C, 35L, 35R",
        "35R, 36L, 36R",
        "35L, 35R, 36R",
        "13R, 17C, 17R, 18L",
        "13R, 17C, 17R, 18R",
        "13R, 17C, 17R",
        "4L, 4R",
        "22L, 22R",
        "22L",
        "13L",
        "13L, 22L",
        "4L",
        "31R",
        "31R, 4L, 4R",
        "22R",
        "22L, 4L, 4R",
        "13L, 22L, 22R",
        "4R",
        "22L, 31L, 31R",
        "22R, 31L, 31R",
        "13R",
        "22L, 22R, 31L",
        "22R, 4L, 4R",
        "13R, 22L",
        "31L, 4L, 4R",
        "13L, 22R",
        "22L, 31L",
        "27",
        "18C, 18L, 18R, 27",
        "27, 36L, 36R",
        "18L, 18R, 27",
        "18C, 27",
        "36C, 36L, 36R, 9",
        "18R, 27",
        "36L, 36R, 9",
        "18C, 18R, 27",
        "27, 36C, 36L",
        "18L, 27",
        "36R, 9",
        "18L, 18R, 27, 36R",
        "9",
        "27, 36R",
        "27, 36C, 36L, 36R",
        "27, 36C, 36R",
        "36C, 36L, 9",
        "36L, 9",
        "27, 36C",
        "27, 36L",
        "18L, 18R, 36L",
        "36C, 9",
        "18C, 18L, 27",
        "18C, 36C",
        "26L, 26R, 27, 30",
        "12, 8L, 8R, 9",
        "12, 8R, 9",
        "12, 8R",
        "26L, 27, 30",
        "26L, 27",
        "26L",
        "8R, 9",
        "26L, 30",
        "26L, 26R, 30",
        "8L, 8R, 9",
        "12, 9",
        "8L, 9",
        "8L, 8R",
        "12, 8L, 9",
        "26L, 26R",
        "26L, 26R, 27",
        "26R, 27, 30",
        "27, 30",
        "12, 8L, 8R",
        "26L, 26R, 27, 8L",
        "30",
        "26R, 27",
        "12",
        "26R, 8L, 8R",
        "27L, 27R, 28C",
        "28C",
        "27L, 28C",
        "27L, 27R",
        "10C, 10R, 9L",
        "10C, 9L, 9R",
        "10C, 9L",
        "27R, 28C",
        "10C",
        "27C, 27R, 28C",
        "27C, 27R",
        "27C, 27L, 28C",
        "27C, 28C",
        "10C, 10R",
        "10C, 9C",
        "10C, 9C, 9L",
        "9C",
        "10R",
        "10C, 10R, 9C",
        "10R, 9L",
        "10L, 9C, 9L",
        "27C, 28C, 28R",
        "22L, 27C, 27R, 28C",
        "27C",
        "28R",
        "10R, 9C, 9L",
        "10L, 9L",
        "27C, 28R",
        "27C, 27R, 28R",
        "10C, 9R",
        "10L",
        "27C, 27R, 28C, 28R",
        "10C, 10L",
        "10L, 9C",
        "10R, 9C",
        "9C, 9L",
        "10C, 28C, 9L",
        "27C, 27L, 27R",
        "27R, 28R",
        "10C, 10L, 10R, 9L",
        "27C, 27R, 28L",
        "27C, 27R, 28C, 28L",
        "28C, 28R",
        "10L, 10R, 9L",
        "22R, 28R",
        "22R, 28C",
        "10L, 10R",
        "10C, 10R, 9C, 9L",
        "22L, 28R",
        "27L, 28R",
        "10L, 4R",
        "28R, 4R",
        "10C, 28C",
        "10C, 4R",
        "28C, 4R",
        "27C, 28C, 9C",
        "22L, 28C",
        "22R, 27L, 27R, 28C",
        "10C, 10R, 27L, 9L",
        "22L, 27C",
        "25L, 26",
        "7R, 8",
        "25L, 25R",
        "7L, 7R",
        "25R",
        "7L",
        "7L, 7R, 8",
        "25L, 25R, 26",
        "7L, 8",
        "7R",
        "25L",
        "25R, 26",
        "16C, 16L",
        "34C, 34L, 34R",
        "34C, 34L",
        "34L",
        "34C, 34R",
        "16C",
        "16C, 16R",
        "34C",
        "16C, 16L, 16R",
        "16L, 34L, 34R",
        "16L, 16R, 34L, 34R",
    ],
    "gufi_flight_destination_airport": [
        "UNKN",
        "DFW",
        "PHL",
        "LAX",
        "MIA",
        "PHX",
        "CLT",
        "DCA",
        "ORD",
        "BHM",
        "PNS",
        "MSY",
        "RDU",
        "TPA",
        "LGA",
        "SEA",
        "PDX",
        "EUG",
        "BNA",
        "BTV",
        "DTW",
        "IAH",
        "PBI",
        "GSP",
        "IAD",
        "OKC",
        "JAX",
        "BWI",
        "DAL",
        "MYR",
        "CHS",
        "AVL",
        "JAC",
        "RIC",
        "LIT",
        "VPS",
        "EZE",
        "PIT",
        "LAS",
        "SAN",
        "SDF",
        "STL",
        "BOS",
        "DEN",
        "ECP",
        "RAP",
        "JFK",
        "ORF",
        "TVC",
        "TLH",
        "CVG",
        "MEM",
        "MSP",
        "CAE",
        "AUS",
        "RNO",
        "RSW",
        "GRR",
        "GNV",
        "HDN",
        "SFO",
        "SRQ",
        "ONT",
        "ROC",
        "GRU",
        "OMA",
        "ALB",
        "SNA",
        "MCI",
        "GPT",
        "TUL",
        "BUF",
        "ABQ",
        "SAV",
        "MDW",
        "SAT",
        "MCO",
        "BZN",
        "BDL",
        "CMH",
        "MAD",
        "TUS",
        "EWR",
        "GSO",
        "LEX",
        "MKE",
        "YUL",
        "ICT",
        "ILM",
        "DAB",
        "JAN",
        "SMF",
        "AGS",
        "STT",
        "BOI",
        "PVD",
        "CLE",
        "SYR",
        "FLL",
        "FSD",
        "IND",
        "MSN",
        "HOU",
        "BTR",
        "SLC",
        "MDT",
        "MTJ",
        "TYS",
        "DSM",
        "MOB",
        "CID",
        "GEG",
        "PWM",
        "BGR",
        "YYZ",
        "CHA",
        "HNL",
        "EYW",
        "HPN",
        "SGF",
        "HSV",
        "GRB",
        "ATW",
        "TRI",
        "SJU",
        "ANC",
        "ROA",
        "OAJ",
        "DAY",
        "FCA",
        "XNA",
        "EGE",
        "FAY",
        "MUC",
        "EVV",
        "SJC",
        "MLB",
        "FRA",
        "SCL",
        "ATH",
        "LIM",
        "STX",
        "PSP",
        "MXP",
        "PTY",
        "DUB",
        "PUJ",
        "BON",
        "SAP",
        "MBJ",
        "RTB",
        "SJD",
        "GUA",
        "KIN",
        "AUA",
        "NAS",
        "LIR",
        "PLS",
        "MTY",
        "CUN",
        "SXM",
        "SAL",
        "VCE",
        "SJO",
        "BCN",
        "PVR",
        "SDQ",
        "UVF",
        "ANU",
        "BZE",
        "SKB",
        "GCM",
        "GDL",
        "JNB",
        "CHO",
        "BOG",
        "ICN",
        "ELP",
        "HND",
        "HSH",
        "LHR",
        "CDG",
        "ADW",
        "MSO",
        "LOS",
        "MEX",
        "BDA",
        "GIG",
        "FCO",
        "UIO",
        "AMS",
        "OGG",
        "GRK",
        "LFI",
        "NBW",
        "NGU",
        "RMS",
        "HHN",
        "FOE",
        "AEX",
        "RIV",
        "TBN",
        "LSF",
        "SCE",
        "AHN",
        "LAN",
        "MAN",
        "PIE",
        "CPS",
        "BED",
        "YEG",
        "MKC",
        "LGB",
        "LWB",
        "LSE",
        "BKL",
        "OAK",
        "TCL",
        "CSG",
        "LYH",
        "PVU",
        "SHV",
        "CLL",
        "GTR",
        "TUP",
        "COU",
        "SBN",
        "CKB",
        "EFD",
        "FTW",
        "FAR",
        "RFD",
        "LNK",
        "GTB",
        "NGF",
        "SKF",
        "BIF",
        "COS",
        "FWH",
        "HRT",
        "LSV",
        "MLU",
        "NJK",
        "NKT",
        "POB",
        "SSC",
        "SUU",
        "SVN",
        "YUM",
        "MGM",
        "VOK",
        "GSB",
        "VAD",
        "PIB",
        "TCM",
        "CWF",
        "GUS",
        "MCN",
        "MDE",
        "QRO",
        "VCV",
        "VQQ",
        "SBD",
        "STI",
        "TAM",
        "BJX",
        "ATL",
        "DLH",
        "TLS",
        "VLD",
        "CRW",
        "BQK",
        "ELH",
        "DHN",
        "GGT",
        "LFT",
        "FWA",
        "BMI",
        "RST",
        "MLI",
        "ABE",
        "ABY",
        "MHH",
        "SLN",
        "BLM",
        "DWH",
        "TEB",
        "BFI",
        "FTY",
        "BVY",
        "ADS",
        "SUA",
        "DSI",
        "ERI",
        "FRG",
        "BCT",
        "SUS",
        "IMT",
        "PDK",
        "APF",
        "JZI",
        "MRK",
        "USA",
        "VRB",
        "UST",
        "LUK",
        "ILG",
        "DPA",
        "TOC",
        "SVH",
        "SSI",
        "IXA",
        "INT",
        "0A9",
        "LAL",
        "HHH",
        "FXE",
        "BWG",
        "ORL",
        "TVI",
        "RBW",
        "BLF",
        "JCI",
        "ASD",
        "FHB",
        "UUV",
        "ROG",
        "TTN",
        "AMA",
        "1A5",
        "ERV",
        "SUX",
        "AAF",
        "MMU",
        "YIP",
        "CQF",
        "ISM",
        "UCY",
        "SWO",
        "BFM",
        "BGE",
        "GKT",
        "SBA",
        "SCF",
        "TWF",
        "TYQ",
        "VNC",
        "VDF",
        "SGT",
        "OPF",
        "CGF",
        "NEW",
        "JWN",
        "AIK",
        "TMA",
        "RAC",
        "VNY",
        "SHD",
        "OCA",
        "HKY",
        "LBB",
        "XNX",
        "DNL",
        "GWO",
        "PWK",
        "BKV",
        "DZJ",
        "OSU",
        "SFB",
        "FCM",
        "EXX",
        "FNT",
        "LEB",
        "DQH",
        "TMB",
        "HDC",
        "RVS",
        "MIV",
        "MDQ",
        "SUN",
        "CCO",
        "LQK",
        "FCI",
        "SGR",
        "THA",
        "PNE",
        "EKI",
        "CRG",
        "RYY",
        "CNI",
        "OCF",
        "BVX",
        "3J7",
        "HTO",
        "27K",
        "AUZ",
        "AND",
        "FFC",
        "LEE",
        "ASE",
        "GOK",
        "HBG",
        "MDD",
        "BUR",
        "FA54",
        "PHF",
        "AUO",
        "FOK",
        "RMG",
        "GON",
        "OLV",
        "CXO",
        "DIJ",
        "UGN",
        "AFW",
        "LCK",
        "VCP",
        "ACY",
        "SGU",
        "CPR",
        "GJT",
        "CRP",
        "FFO",
        "LAW",
        "NBC",
        "PAM",
        "BAD",
        "SWF",
        "YMX",
        "POP",
        "AVP",
        "CUR",
        "BGI",
        "GND",
        "MHT",
        "CZM",
        "ROW",
        "LAF",
        "YOW",
        "PTK",
        "BKS",
        "HYA",
        "GMU",
        "UTM",
        "FMY",
        "DEC",
        "ACK",
        "MYL",
        "LCH",
        "CEU",
        "BUY",
        "GAI",
        "MFD",
        "GVL",
        "HNZ",
        "MTH",
        "SRW",
        "CVC",
        "MDN",
        "ESN",
        "CZL",
        "PQI",
        "SEF",
        "AZO",
        "JVY",
        "AGC",
        "CLD",
        "PGD",
        "MSL",
        "MRH",
        "CTH",
        "HAR",
        "DET",
        "JPX",
        "MVL",
        "STP",
        "UES",
        "CEF",
        "VES",
        "CON",
        "TEX",
        "GED",
        "LBE",
        "MJX",
        "4I3",
        "GGE",
        "LOT",
        "UOX",
        "HQU",
        "CMI",
        "CAK",
        "RDG",
        "HVN",
        "CLU",
        "SPZ",
        "YNG",
        "ISO",
        "HUM",
        "BRY",
        "1G3",
        "MLJ",
        "BBX",
        "DYB",
        "STE",
        "BFT",
        "BCB",
        "SPA",
        "PGV",
        "MRN",
        "ONX",
        "MTN",
        "BOW",
        "RKH",
        "VDI",
        "ALN",
        "ITH",
        "INF",
        "ISW",
        "MQJ",
        "EAU",
        "POU",
        "TTA",
        "PWA",
        "WST",
        "RMN",
        "LZU",
        "BHB",
        "OXC",
        "RCZ",
        "BFP",
        "BJC",
        "MQY",
        "WWD",
        "EYE",
        "CSV",
        "CZT",
        "FDY",
        "MTV",
        "CHN",
        "EWN",
        "RBD",
        "SBM",
        "DMW",
        "PSK",
        "TYR",
        "PEO",
        "SOP",
        "AIZ",
        "CGI",
        "5B2",
        "FQD",
        "PSM",
        "FWS",
        "MKG",
        "HGR",
        "WGO",
        "HBI",
        "SFM",
        "HAO",
        "FLO",
        "PLN",
        "BIV",
        "LNS",
        "MEO",
        "F45",
        "DLZ",
        "AMW",
        "IPJ",
        "BPT",
        "EQY",
        "SDX",
        "SMX",
        "MVY",
        "LCI",
        "CXU",
        "APA",
        "CDN",
        "BTP",
        "LBT",
        "87I",
        "0G7",
        "OFP",
        "BTL",
        "MNZ",
        "BAZ",
        "GGG",
        "VJI",
        "SUT",
        "MAF",
        "ISP",
        "PIA",
        "LWC",
        "IKV",
        "GIF",
        "AKC",
        "BDR",
        "GXY",
        "LVK",
        "ASN",
        "MRY",
        "HCR",
        "U42",
        "FFT",
        "TOL",
        "NUQ",
        "APC",
        "BKG",
        "AZS",
        "FPO",
        "SBY",
        "HTS",
        "YWG",
        "YYC",
        "YVR",
        "PRB",
        "SBP",
        "TSM",
        "RIL",
        "FNL",
        "HBV",
        "FYG",
        "CWA",
        "GUC",
        "SAF",
        "DVT",
        "DWX",
        "TKI",
        "SAA",
        "PIR",
        "AXN",
        "MHR",
        "PRC",
        "HLN",
        "GOO",
        "DNA",
        "SHR",
        "SPS",
        "PKD",
        "TOA",
        "DRO",
        "TXK",
        "8A0",
        "BLI",
        "ADM",
        "RSN",
        "PWY",
        "TRM",
        "PGO",
        "GEU",
        "CEZ",
        "SMO",
        "PGA",
        "OGD",
        "CYS",
        "YKM",
        "COD",
        "DIK",
        "PUB",
        "MVW",
        "9TE2",
        "MKT",
        "MOT",
        "SOW",
        "LXV",
        "TKF",
        "ELD",
        "GCC",
        "IDA",
        "3U3",
        "HIO",
        "JVL",
        "FLG",
        "TME",
        "BIL",
        "EKS",
        "PYM",
        "EKO",
        "LWS",
        "OJC",
        "COE",
        "OTH",
        "SPW",
        "EDC",
        "RNM",
        "LND",
        "LAR",
        "O89",
        "UIN",
        "TIW",
        "CNY",
        "CMA",
        "STJ",
        "JWY",
        "WRL",
        "UDD",
        "MHK",
        "VGT",
        "CLM",
        "AEJ",
        "FAT",
        "BIS",
        "HRL",
        "CPV",
        "AIA",
        "ALS",
        "DVL",
        "EAR",
        "XWA",
        "ATY",
        "RIW",
        "GTF",
        "RKS",
        "RDM",
        "PSC",
        "JMS",
        "MFR",
        "BFL",
        "LBL",
        "WYS",
        "LBF",
        "HOB",
        "HYS",
        "BFF",
        "PAE",
        "DDC",
        "JLN",
        "VEL",
        "BIH",
        "ACV",
        "BTM",
        "FOD",
        "VCT",
        "HIF",
        "KOA",
        "LIH",
        "PUW",
        "LCQ",
        "BQN",
        "NRT",
        "GYR",
        "ILN",
        "GYY",
        "CUU",
        "MFE",
        "SLP",
        "ZIH",
        "MLM",
        "MZT",
        "DGO",
        "OAX",
        "TGU",
        "FAI",
        "AKL",
        "OSH",
        "LRD",
        "FSM",
        "ZLO",
        "BRO",
        "STS",
        "SGH",
        "T82",
        "MBS",
        "TDZ",
        "HYI",
        "ABI",
        "CDS",
        "DTO",
        "FPR",
        "T30",
        "IDP",
        "DZB",
        "GSH",
        "HII",
        "RTN",
        "JBR",
        "AQO",
        "HOT",
        "VBT",
        "LUD",
        "T89",
        "HDO",
        "CCR",
        "SNK",
        "CVX",
        "TQH",
        "WDG",
        "OUN",
        "BBD",
        "BMQ",
        "AAO",
        "JEF",
        "GTU",
        "SEP",
        "GUF",
        "MWL",
        "LXT",
        "MEV",
        "ACT",
        "3T5",
        "LRU",
        "GKY",
        "PBF",
        "FST",
        "ZCL",
        "GRI",
        "SJT",
        "MID",
        "ACA",
        "DRT",
        "GCK",
        "AGU",
        "TRC",
        "HUX",
        "SPI",
        "LAP",
        "LTO",
        "HMO",
        "DOH",
        "TLV",
        "CLO",
        "EOH",
        "GEO",
        "DEL",
        "YQX",
        "BRU",
        "ACC",
        "DBV",
        "ARN",
        "EDI",
        "PRG",
        "GOBD",
        "CPH",
        "KEF",
        "NCE",
        "LIS",
        "ZRH",
        "EDF",
        "DBQ",
        "HEL",
        "HOP",
        "WRI",
        "BGM",
        "ARB",
        "NCO",
        "CKI",
        "GPC",
        "EWB",
        "HSA",
        "OWD",
        "GFL",
        "OCE",
        "DAN",
        "LKP",
        "RKD",
        "JYO",
        "PSF",
        "MGW",
        "GWW",
        "2W5",
        "IPT",
        "RUT",
        "SLK",
        "WVL",
        "HMP",
        "EEN",
        "MFV",
        "LEW",
        "ORH",
        "SEG",
        "BXM",
        "PBG",
        "BAF",
        "GYE",
        "CTG",
        "POS",
        "PAP",
        "LGW",
        "PTP",
        "HAV",
        "PSE",
        "MZJ",
        "CNM",
        "HCC",
        "11R",
        "GDJ",
        "LPR",
        "CKM",
        "38XS",
        "HFJ",
        "LUG",
        "COT",
        "CKZ",
        "BRD",
        "PAH",
        "1M4",
        "PWG",
        "JXN",
        "MBG",
        "VUJ",
        "RZR",
        "IRS",
        "AWM",
        "EET",
        "SBO",
        "ILL",
        "AIO",
        "MGY",
        "ENL",
        "DXE",
        "IJX",
        "AJR",
        "MKL",
        "MRB",
        "BMG",
        "BWD",
        "ENW",
        "STN",
        "TLC",
        "CGN",
        "LGG",
        "KIX",
        "ARA",
        "DXB",
        "NQA",
        "SIN",
        "TIJ",
        "CBM",
        "DMA",
        "NKX",
        "DOV",
        "NIP",
        "SVD",
        "BAQ",
        "PEI",
        "MAO",
        "PLL",
        "CMW",
        "HOG",
        "SCU",
        "MHPA",
        "SNU",
        "VRA",
        "TVSA",
        "PBM",
        "MGA",
        "MVD",
        "NQX",
        "TIX",
        "3J1",
        "EVB",
        "X07",
        "ELM",
        "PPM",
        "FIN",
        "DED",
        "EVY",
        "BEH",
        "MWK",
        "ONH",
        "EBA",
        "EUF",
        "MWA",
        "20V",
        "RME",
        "EYF",
        "PXE",
        "ASH",
        "AVW",
        "BXS",
        "AXG",
        "FDF",
        "DOM",
        "AXA",
        "CTM",
        "ADZ",
        "MEZ",
        "ICR",
        "ARV",
        "ANE",
        "ACB",
        "ATO",
        "MQT",
        "OTM",
        "HYR",
        "MGN",
        "LPO",
        "BLV",
        "MBL",
        "SXK",
        "VPC",
        "BDE",
        "MBT",
        "ALO",
        "LRJ",
        "IRK",
        "PCW",
        "BNW",
        "BJJ",
        "RHI",
        "PHN",
        "MKJ",
        "2G9",
        "LWA",
        "MCW",
        "DTL",
        "GLD",
        "UMP",
        "HKA",
        "MGC",
        "CIU",
        "PEA",
        "STC",
        "ASX",
        "PWT",
        "YQB",
        "HKG",
        "CMX",
        "JST",
        "OGS",
        "ABR",
        "GFK",
        "APN",
        "MDH",
        "GUM",
        "TPE",
        "PVG",
        "YYR",
        "LLR",
        "TPL",
        "MSC",
        "6S0",
        "RNT",
        "BJI",
        "SPK",
        "MMH",
        "MOD",
        "AZA",
        "CNE",
        "TCC",
        "GLS",
        "LVM",
        "TDW",
        "AEG",
        "RKP",
        "SLE",
        "SMN",
        "CHD",
        "RDD",
        "SLT",
        "JER",
        "HSG",
        "ALE",
        "C29",
        "HRF",
        "WVI",
        "MNM",
        "IOW",
        "RUI",
        "LVS",
        "TVL",
        "CFT",
        "38S",
        "P20",
        "IPL",
        "DPH",
        "CUL",
        "FHU",
        "NZY",
        "JNU",
        "SIT",
        "KTN",
        "PSG",
        "WRG",
        "CDV",
        "OME",
        "ADQ",
        "AKN",
        "YXY",
        "ALW",
        "SFF",
        "SZT",
        "UAO",
        "MMV",
        "DLN",
        "RBG",
        "SAC",
        "EAT",
        "YYJ",
        "YLW",
        "EIL",
    ],
    "airline": AIRLINES,
    "year": ["UNK", "2020", "2021", "2022"],
    "aircraft_engine_class": ["OTHER", "PISTON", "TURBO", "JET"],
    "major_carrier": ["UNK", "AAL", "UAL", "DAL", "FDX", "JBU"],
    "flight_type": ["UNK", "SCHEDULED_AIR_TRANSPORT", "GENERAL_AVIATION"],
    "aircraft_type": [
        "UNK",
        "B738",
        "A320",
        "A319",
        "A321",
        "A21N",
        "B38M",
        "B788",
        "B739",
        "B39M",
        "E75L",
        "CRJ9",
        "CRJ7",
        "B752",
        "B712",
        "B764",
        "A333",
        "B763",
        "A332",
        "B753",
        "A359",
        "BCS1",
        "A339",
        "A20N",
        "B762",
        "BCS3",
        "CRJ2",
        "E170",
        "GL5T",
        "GLF4",
        "GLEX",
        "CL60",
        "C68A",
        "E55P",
        "C56X",
        "CL35",
        "C680",
        "C700",
        "E145",
        "A306",
        "DC10",
        "MD11",
        "E190",
        "E75S",
        "CRJ1",
        "B737",
        "B77W",
        "B772",
        "B78X",
        "G280",
        "GL7T",
        "H25B",
        "CL30",
        "E135",
        "B789",
        "B77L",
        "B744",
        "B773",
        "B748",
        "A30B",
        "B722",
        "RV8",
        "C560",
        "B732",
        "DH8D",
    ],
}

INT16_COLUMNS: tuple[str, ...] = (
    "minutes_until_pushback",
    "minutes_until_etd",
    "deps_3hr",
    "deps_30hr",
    "arrs_3hr",
    "arrs_30hr",
    "deps_taxiing",
    "arrs_taxiing",
    "exp_deps_15min",
    "exp_deps_30min",
    "temperature",
    "wind_direction",
    "wind_speed",
    "wind_gust",
    "cloud_ceiling",
    "visibility",
    "gufi_timestamp_until_etd",
    "feat_5_gufi",
    "feat_5_estdep_next_30min",
    "feat_5_estdep_next_60min",
    "feat_5_estdep_next_180min",
    "feat_5_estdep_next_360min",
)

FLOAT32_COLUMNS: tuple[str, ...] = (
    "delay_30hr",
    "standtime_30hr",
    "dep_taxi_30hr",
    "arr_taxi_30hr",
    "delay_3hr",
    "standtime_3hr",
    "dep_taxi_3hr",
    "arr_taxi_3hr",
    "1h_ETDP",
)

CATEGORICAL_INT8_COLUMNS: list[str] = [
    "cloud_ceiling",
    "visibility",
    "month",
    "day",
    "hour",
    "minute",
    "weekday",
]
